news/urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('news_list/', views.news_list, name='news_list'),
    path(
        'comments_count_field/<pk>/',
        views.comments_count_field,
        name='comments_count_field',
    ),
    path('more/<pk>/', views.more, name='more'),
    path('news_create/', views.news_create, name='news_create'),
    path('news_edit/<pk>/', views.news_edit, name='news_edit'),
    path('news_delete/<pk>/', views.news_delete, name='news_delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url=reverse_lazy('news:news_list'))),
    path('news/', include('news.urls'), name='news'),
]

news/models.py
from django.db import models


class News(models.Model):
    title = models.CharField(max_length=255, unique=True)
    subtitle = models.CharField(max_length=255)
    text = models.TextField()

news/forms.py
from django import forms

from . import models


class NewsForm(forms.ModelForm):
    class Meta:
        model = models.News
        fields = ['title', 'subtitle', 'text']

news/views.py
import random
from http import HTTPStatus
from time import sleep

from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.views.decorators.http import require_http_methods

from . import forms, models


@require_http_methods(['GET'])
def news_list(request: HttpRequest) -> HttpResponse:
    page = request.GET.get('page', 1)
    search = request.GET.get('search')

    qs = models.News.objects.all()

    if search is not None:
        qs = qs.filter(Q(title__icontains=search) | Q(subtitle__icontains=search))

    news_list = Paginator(qs.order_by('-id'), 6, 5).page(page)

    if request.headers.get('HX-Trigger') in ['paginator', 'search']:
        template_name = 'news/includes/news_cards.html'
    else:
        template_name = 'news/news_list.html'

    return render(request, template_name, {'news_list': news_list})


@require_http_methods(['GET'])
def comments_count_field(request: HttpRequest, pk) -> HttpResponse:
    sleep(random.randint(0, 3))
    comments_count = random.randint(0, 5)
    return render(
        request,
        'news/includes/comments_count_field.html',
        {'comments_count': comments_count},
    )


@require_http_methods(['GET'])
def more(request: HttpRequest, pk) -> HttpResponse:
    news = models.News.objects.get(pk=pk)
    sleep(random.randint(0, 2))
    if random.randint(0, 1):
        messages.error(request, 'Error while fetching.')
        return render(
            request,
            'news/fragments/more_500.html',
            {'news': news},
            status=HTTPStatus.INTERNAL_SERVER_ERROR,
        )
    return render(request, 'news/fragments/more.html', {'news': news})


@require_http_methods(['GET', 'POST'])
def news_create(request: HttpRequest) -> HttpResponse:
    form = forms.NewsForm(request.POST or None)

    if request.method == 'GET':
        return render(request, 'news/news_create.html', {'form': form})

    if not form.is_valid():
        messages.error(request, 'Error on create news.')
        response = render(request, 'news/news_create.html', {'form': form})
        response['HX-Push-Url'] = 'false'
        return response

    messages.success(request, 'News created with success')
    form.save()
    return redirect('news:news_list')


@require_http_methods(['GET', 'POST'])
def news_edit(request: HttpRequest, pk) -> HttpResponse:
    news = models.News.objects.get(pk=pk)
    form = forms.NewsForm(request.POST or None, instance=news)

    if request.method == 'GET':
        return render(request, 'news/news_edit.html', {'form': form})

    if not form.is_valid():
        messages.error(request, 'Error on update news.')
        response = render(request, 'news/news_edit.html', {'form': form})
        response['HX-Push-Url'] = 'false'
        return response

    messages.success(request, 'News updated with success.')
    form.save()
    return redirect('news:news_list')


@require_http_methods(['DELETE'])
def news_delete(request: HttpRequest, pk) -> HttpResponse:
    models.News.objects.filter(pk=pk).delete()
    messages.success(request, 'News removed with success')
    return render(request, 'fragments/messages.html')

news/templates/news/fragments/more.html
{% include 'fragments/messages.html' %}

<div class="offcanvas-body">
  <p>{{ news.text }}</p>
</div>

news/templates/news/fragments/more_500.html
{% include 'fragments/messages.html' %}

<div class="offcanvas-body">
  {% include 'includes/spinner.html' %}
  <div class="hide-when-htmx-indicator-before">
    <p>Error while fetching</p>
    <button
      class="btn btn-primary d-flex justify-content-center align-items-center"
      hx-get="{% url 'news:more' news.pk %}"
      hx-target="closest .offcanvas-body"
      hx-target-error="closest .offcanvas-body"
      hx-trigger="click"
      hx-swap="outerHTML"
      hx-indicator="previous [role='status']"
      >Click here to try again</button>
  </div>
</div>

news/templates/news/includes/comments_count_field.html
<p>Comments: {{ comments_count }}</p>

news/templates/news/includes/news_cards.html
{% for news in news_list %}
  <article class="news col-lg-3 col-md-4 col-sm-6 col-12 mb-4">
    <div class="overflow-hidden d-flex justify-content-center align-items-center rounded" style="height: 200px">
      <img src="https://picsum.photos/300/300?{{ news.title }}" class="object-fit-cover d-block w-100" alt="{{ news.title }}">
    </div>
    <div class="mt-4 px-1">
      <h3>{{ news.title }}</h3>
      <p>{{ news.subtitle }}</p>
      <div
        hx-get="{% url 'news:comments_count_field' news.pk %}"
        hx-trigger="revealed"
        hx-swap="outerHTML"
        hx-indicator="find [role='status']"
        >
        {% include 'includes/secondary_spinner.html' %}
      </div>
    </div>
    <div>
      <button
        id="btn-open-more-{{ news.pk }}"
        type="button"
        class="btn btn-primary"
        data-bs-toggle="offcanvas"
        data-bs-target="#offcanvas-{{ news.pk }}"
        >More</button>
      <div id="offcanvas-{{ news.pk }}" class="offcanvas offcanvas-start" tabindex="-1">
        <div class="offcanvas-header">
          <h2 class="offcanvas-title">More</h2>
          <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"></button>
        </div>
        <div
          class="offcanvas-body"
          hx-get="{% url 'news:more' news.pk %}"
          hx-trigger="click from:#btn-open-more-{{ news.pk }}"
          hx-swap="outerHTML"
          hx-target-error="this"
          hx-indicator="find [role='status']"
          >
          {% include 'includes/spinner.html' %}
        </div>
      </div>
      <a href="{% url 'news:news_edit' news.pk %}" class="btn btn-secondary">Edit</a>
      <button
        type="button"
        class="btn btn-danger"
        hx-delete="{% url 'news:news_delete' news.pk %}"
        hx-target="closest .news"
        hx-swap="delete"
        hx-confirm="Do you really want to remove the news?"
        >Remove</button>
    </div>
  </article>
{% endfor %}
{% if news_list.has_next %}
  <div
    id="paginator"
    class="text-center m-4"
    hx-get="{% url 'news:news_list' %}?page={{ news_list.next_page_number }}"
    hx-trigger="revealed"
    hx-swap="outerHTML"
    hx-indicator="find [role='status']"
    >
    {% include 'includes/spinner_grow.html' %}
  </div>
{% endif %}

news/templates/news/news_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block main %}
  <h1>Add news</h1>

  <form method="post">
    {{ form|crispy }}
    {% include 'includes/form_buttons.html' %}
  </form>
{% endblock main %}

news/templates/news/news_edit.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block main %}
  <h1>Update news</h1>

  <form method="post">
    {{ form|crispy }}
    {% include 'includes/form_buttons.html' %}
  </form>
{% endblock main %}

news/templates/news/news_list.html
{% extends 'base.html' %}

{% block main %}
  <h1 class="mb-5">News</h1>

  <div class="row">
    <div class="col-lg-3 col-md-4 col-sm-6 col-12">
      <input
        id="search"
        type="search"
        name="search"
        value="{{ request.GET.search }}"
        class="textinput form-control form-control-lg mb-4"
        placeholder="Search"
        hx-get="{% url 'news:news_list' %}"
        hx-trigger="search, keyup delay:500ms changed"
        hx-target="next section"
        hx-push-url="true">
    </div>
  </div>

  <section class="row">
    {% include 'news/includes/news_cards.html' %}
  </section>
{% endblock main %}

templates/base.html
<!doctype html>
<html lang="pt-BR">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="htmx-config" content='{"selfRequestsOnly":false}'>
  
  <title>News</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <!-- IMPORTANTE: Ao usar hx-boost="true", todas as declarações de scripts deve ser movidas para 
   o head para impedir que elas sejam redeclaradas durante o swapping de páginas -->
  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>

  <script src="https://unpkg.com/htmx.org@2.0.0"></script>
  <script src="https://unpkg.com/htmx-ext-response-targets@2.0.0/response-targets.js"></script>

  <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>

  <style>
    .htmx-indicator{
      display: none;
      transition: opacity 500ms ease-in;
    }
    .htmx-request .htmx-indicator {
      display: inline-block;
    }
    .htmx-request.htmx-indicator {
      display: inline-block;
    }
    .htmx-indicator.htmx-request + .hide-when-htmx-indicator-before {
      display: none;
    }
  </style>
</head>

<body hx-boost="true" hx-ext="response-targets">
  <div hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <div id="toast-container" class="toast-container position-fixed p-3 top-0 end-0">
      {% include 'includes/messages.html' %}
    </div>
    <nav class="bg-primary">
      <div class="container">
        <ul class="d-flex align-items-center py-3 gap-3 list-unstyled text-white">
          <li><a href="{% url 'news:news_list' %}" class="text-white text-decoration-none display-6">home</a></li>|
          <li><a href="{% url 'news:news_create' %}" class="text-white text-decoration-none display-6">add news</a></li>
        </ul>
      </div>
    </nav>
    <main class="container mt-4">
      {% block main %}
      {% endblock main %}
    </main>
  </div>
</body>

</html>

templates/fragments/messages.html
{% if messages %}
  <div id="toast-container" class="toast-container position-absolute p-3 bottom-0 end-0" hx-swap-oob="afterbegin">
    {% include 'includes/messages.html' %}
  </div>
{% endif %}

templates/includes/form_buttons.html
<div class="d-flex justify-content-center gap-2">
  <button type="submit" class="btn btn-primary">Save</button>
  <button type="button" class="btn btn-secondary" x-data @click="history.back()">Cancel</button>
</div>

templates/includes/messages.html
{% for message in messages %}
  <div
    class="toast align-items-center {{ message.tags }} border-0"
    role="alert"
    data-bs-delay="5000"
    x-data="{ toast: bootstrap.Toast.getOrCreateInstance($el) }"
    x-init="
      !toast.isShown() && toast.show();
      setTimeout(() => {
        toast.hide();
        // wait animation
        setTimeout(() => $el.remove(), 500);
      }, 5000);
    ">
    <div class="d-flex">
      <div class="toast-body">
        {{ message }}
      </div>
      <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>
{% endfor %}

templates/includes/secondary_spinner.html
<div class="htmx-indicator spinner-border spinner-border-sm" role="status">
  <span class="visually-hidden">Loading...</span>
</div>

templates/includes/spinner.html
<div class="htmx-indicator spinner-border" role="status">
  <span class="visually-hidden">Loading...</span>
</div>

templates/includes/spinner_grow.html
<div class="htmx-indicator spinner-grow" role="status">
  <span class="visually-hidden">Loading...</span>
</div>